version: '3'

services:

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jh76rff5rft
      - MYSQL_PASSWORD=jh76rff5rft
      - MYSQL_USER=main
      - MYSQL_DATABASE=store

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
